ROOT_PATH: "/media/chge7185/HDD1/datasets/Skycloud360/360degree_cloudlabel"
DATASET:
    NAME: "skycloud360"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    IGNORE_INDEX: -1
    WORKERS: 4
TRAIN:
    EPOCHS: 200
    BATCH_SIZE: 16
    CROP_SIZE: (512,512)
    BASE_SIZE: 1024
    BACKBONE_PRETRAINED_PATH: "pretrained/mit_b2.pth"
    MODEL_SAVE_DIR: 'workdirs/skycloud/trans4pass_plus_small_512x512/'
    APEX: False
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: "workdirs/skycloud/trans4pass_plus_small_512x512/trans4pass_plus_small_512x512.pth"
    CROP_SIZE: (1664, 832)

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.00005
    OHEM: False

MODEL:
    MODEL_NAME: "Trans4PASS"
    BACKBONE: "trans4pass_v2"
    EMB_CHANNELS: 128
    USE_DCN: [True, False, False, False]
    USE_DEDE: [True, True, True, True]

AUG:
    CROP: True